import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

import Card from '../components/Card'
import News from '../components/News'
import { NavItem, VideoItem, NewsItem, CardIdiom } from '../lib/types'
import { contentOne, contentTwo, contentBerita, contentVideo } from '../lib/data'
import dynamic from 'next/dynamic'
import Navbar from '../components/Navbar'
import TimeAgo from 'javascript-time-ago'

import en from 'javascript-time-ago/locale/en.json'
import id from 'javascript-time-ago/locale/id.json'
import Footer from '../components/Footer'
import ContactUs from '../components/ContactUs'
import JoinUs from '../components/JoinUs'

TimeAgo.addDefaultLocale(en)
TimeAgo.addLocale(id)

type Props = {
  navItem: NavItem;
  videoItem: VideoItem[];
  newsItem: NewsItem[];
  cardIdiom: CardIdiom[];
}

const Home: NextPage<Props> = ({ navItem, videoItem, newsItem, cardIdiom }) => {
  const Player = dynamic(() => import('../components/Video'))

  return (
    <div className="flex flex-col">
      <Head>
        <title>Golkar Sarolangun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-golkar.ico" />
      </Head>

      <main className="flex flex-col">
        <div className='2xl:hidden z-50 sticky top-0'>
          <Navbar nav-items={navItem['nav-items']} />
        </div>
        <section className='w-full h-[40vh] sm:h-[72vh] md:h-[86vh] lg:h-[90vh] xl:h-[110vh] bg-golkar 2xl:bg-cover bg-contain bg-no-repeat 2xl:bg-center 2xl:bg-fixed z-10'>
          <div className='hidden 2xl:block mt-6 z-50'>
            <Navbar nav-items={navItem['nav-items']} />
          </div>
          <div className='hidden sm:block xl:py-10 xl:mt-10 sm:py-10 sm:mt-16 md:mt-20 lg:mt-40'>
            <JoinUs image-kita-satu={navItem['image-kita-satu']} description={navItem['description']} />
          </div>
        </section>

        <section className='sm:hidden'>
          <JoinUs image-kita-satu={navItem['image-kita-satu']} description={navItem['description']} />
        </section>

        <section className='xl:bg-golkar-grey bg-contain bg-no-repeat bg-center xl:h-[450px] bg-none w-full p-0 m-0 sm:px-10 mt-10 z-0'>
          <div className='bg-white bg-opacity-75'>
            <div className='grid grid-cols-1 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-2 gap-0 p-2 sm:p-0'>
              {cardIdiom.map((item, i) => <Card key={i} payload={item} index={i} />)}
            </div>
          </div>
        </section>

        <section className='flex flex-col sm:p-10'>
          <div className='text-left text-2xl sm:text-3xl md:text4xl lg:text-5xl pl-4 xl:mt-10'>Berita</div>
          <div className='text-right text-md lg:text-xl text-cyan-400 pr-4 my-5'>Lihat Semua</div>
          <div className='grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-4 gap-5 p-2'>
            {newsItem.map((value, i) => <News key={i} payload={value} />)}
          </div>
        </section>

        <section className='2xl:p-20'>
          <div className='2xl:bg-golkar-video 2xl:h-[1000px] bg-contain bg-center 2xl:flex 2xl:flex-col 2xl:items-center 2xl:self-center'>
            <div className='text-center text-2xl sm:text-3xl md:text4xl lg:text-5xl 2xl:pt-20 pb-10'>
              <div className='sm:mt-10'>Mars & Hymne</div>
              <div className=''>Partai Golkar</div>
            </div>
            <div className='flex flex-col 2xl:flex-row p-4 2xl:px-36'>
              {videoItem.map((value, i) => <Player key={i} payload={value} />)}
            </div>
          </div>
        </section>

        <ContactUs />

      </main>
      <Footer />
    </div>
  )
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const navItem = contentOne;
  const videoItem = contentVideo;
  const cardIdiom = contentTwo;
  const newsItem = contentBerita;
  return {
    props: {
      navItem,
      videoItem,
      cardIdiom,
      newsItem
    }
  };
};

export default Home
