import Head from 'next/head'

export default function Home() {
  return (
    <div className="flex flex-col">
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col">
         <section className='w-full h-screen bg-golkar bg-cover bg-center'>
          <nav className='flex flex-row py-10 px-6'>
              <div className='basis-1/12 flex justify-end self-center'>
                <span className='inset-y-0 right-0 border-r-2 border-white px-2'>
                  <img src='logo.png' alt='logo-golkar' className='bg-local w-14 h-14 mr-5'/>
                </span> 
              </div>
              <ol className='basis-1/2 flex flex-row justify-around uppercase font-sans text-slate-700 self-center'>
                <li>Profil</li>
                <li>Pejabat</li>
                <li>Hasta Karya</li>
                <li>Ormas Sayap</li>
                <li>PPID</li>
                <li>Lembaga</li>
              </ol>
              <div className='basis-1/2 flex justify-around self-center'>
                <div className="xl:w-96 self-center">
                    <div className="flex flex-row w-full rounded">
                      <input type="search" className="form-control flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" placeholder="Search" aria-label="Search" aria-describedby="button-addon2" />
                      <span className="input-group-text flex items-center px-3 py-1.5 text-base font-normal text-gray-700 text-center whitespace-nowrap rounded" id="basic-addon2">
                        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" className="w-4" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                          <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                        </svg>
                      </span>
                    </div>
                  </div>
              </div>
            </nav>
            <section className='flex flex-col py-10 px-10'>
              <div className='flex flex-row justify-around'>
                <div className="basis-1/2 font-sans">
                  <span className='text-center text-9xl'>
                    <h1>Golkar</h1>
                    <h1>Sarolangun</h1>
                  </span>
                  <span>
                    <a href='#'><h2 className="text-center text-xl mt-6 font-bold">Bergabung Menjadi Anggota</h2></a>
                  </span>
                </div>
                <div className='basis-1/2'></div>
              </div>
              <div className='flex flex-col self-center mt-56'>
                <div className='flex w-72 self-center'>
                  <img src='kita-satu.png' alt='kita-satu' className='bg-local w-full'/>
                </div>
                <p className='text-center w-[500px] mt-5'>
                  Partai Golongan Karya (Partai Golkar), sebelumnya bernama Golongan Karya (Golkar) dan Sekretariat Bersama Golongan Karya (Sekber Golkar), Partai Golkar merupakan salah satu partai politik tertua di Indonesia. Partai Golkar didirikan pada tanggal 20 Oktober 1964 oleh Soeharto dan Suhardiman.
                </p>
              </div>
            </section>
        </section>
        <section className='flex justify-center self-center bg-yellow-200 h-96 w-[900px] m-10 rounded-2xl'>
          <div className='grid grid-cols-2 grid-flow-row gap-4 place-items-stretch'>
            <div className='w-full'>Tugas & Fungsi</div>
            <div >Visi & Misi</div>
            <div >Sejarah</div>
            <div >Profil Pimpinan</div>
          </div>
        </section>
        

      </main>
      <hr className='my-5 border-t-1'/>
      <footer className='flex justify-center'>
        © 2022 Partai Golkar Sarolangun, All right reserved.
      </footer>
    </div>
  )
}
